
         
        // Array to hold the selected image IDs
        var selectedImages = [];

        /* Function to toggle selection, it has an argument event,event object 
        contains information about the event, such as the type and
         the target element (the clicked image)*/
        function toggleSelection(event) {
            var img = event.target; /* gets the element that triggers the event, the clicked img */
            var imgId = img.id; /* the clicked img id */
            //check if the image had been clicked (if its in the selectedimages array)
            if (selectedImages.includes(imgId)) {
                // If already selected, remove selection using splice method
                selectedImages.splice(selectedImages.indexOf(imgId), 1);
                //remove the img element selected from class 'selected-region for styling to enhance visibility
                img.classList.remove('selected-region');
            } else {
                // If not selected, add to selection
                selectedImages.push(imgId);
                 //add the img element selected to class 'selected-region for styling to enhance visibility
                img.classList.add('selected-region');
                
            }
        }
        

        // Add click event listeners to the images
        /* querySelectorAll() a method of the document object in JavaScript,it returnms a node list of selected 
        elements.  forEach is a loop accessing every selected img element,  takes a callback function 
        as an argument, asyncronious operation to occur after querySelectoralAll() as been sucessfull*/
        document.querySelectorAll('#CAP img').forEach(img => {
            /* addEventListener attaches an event listener to the <img> element. click indicates which type of event
             to listen for.toggleSelection   specifies the function to call when the event is triggered. */
            img.addEventListener('click', toggleSelection);
        });
         

        // Function to handle form submission
        function submitCaptcha() {
            /* set the value of ellement with id "hidden" to selectedimages array */
    document.getElementById("hidden").value = selectedImages;
     /* .submit () When called on a form element, it submits the form to the server, 
    effectively triggering its submission as if the user had clicked a submit button.*/
    document.getElementById("captchaForm").submit();
                 }
     
                // make the select image to be radom
                
                //calling method rand () onload event
                onload=rand();
                
                function rand(){
                   var dog = "dogcapture.jpeg";
                    var greenTruck = "truckcapture.jpeg";
                    var TarmarkTruck = "truck1.jpeg";
                    //set array pictureArray variables dog, greenTruck, TarmarkTRruck
                var pictureArray=[dog,greenTruck,TarmarkTruck];
                // Select a random picture from the array
              /* * operator in this context is to scale the random number generated by Math.random() 
              to fit within the range of valid indices for the pictureArray */
                var x = pictureArray[Math.floor(Math.random() * pictureArray.length)];
                 
                //set a variable to the valeu of element in className given
               var elementsOne = document.getElementsByClassName("one");
        var elementsTwo = document.getElementsByClassName("two");
        var elementsThree = document.getElementsByClassName("three");

        var heading=document.getElementById("heading");

        if (x === dog) {
            heading.innerText="Select regions with a dog";
            // using a control structure to tset the url in the elements under the given className
            for (var i = 0; i < elementsOne.length; i++) {
                elementsOne[i].src = "dogcapture.jpeg";
                elementsOne[i].alt = "dog";
            }
            for (var i = 0; i < elementsTwo.length; i++) {
                elementsTwo[i].src = "truckcapture.jpeg";
                elementsTwo[i].alt = "truck with green background";
            }
            for (var i = 0; i < elementsThree.length; i++) {
                elementsThree[i].src = "truck1.jpeg";
                elementsThree[i].alt = "truck on the tarmac road";
            }
        } else if (x === greenTruck) {
            heading.innerText="Select regions with a Truck and green Vegetation";
            for (var i = 0; i < elementsOne.length; i++) {
                elementsOne[i].src = "truckcapture.jpeg";
                elementsOne[i].alt = "truck with green background";
            }
            for (var i = 0; i < elementsTwo.length; i++) {
                elementsTwo[i].src = "dogcapture.jpeg";
                elementsTwo[i].alt = "dog";
            }
            for (var i = 0; i < elementsThree.length; i++) {
                elementsThree[i].src = "truck1.jpeg";
                elementsThree[i].alt = "truck on the tarmac road";
            }
        } else {
            // x === TarmarkTruck
            heading.innerText="Select regions with a truck on the tarmark road";
            for (var i = 0; i < elementsOne.length; i++) {
                elementsOne[i].src = "truck1.jpeg";
                elementsOne[i].alt = "truck on the tarmac road";
            }
            for (var i = 0; i < elementsTwo.length; i++) {
                elementsTwo[i].src = "truckcapture.jpeg";
                elementsTwo[i].alt = "truck with green background";
            }
            for (var i = 0; i < elementsThree.length; i++) {
                elementsThree[i].src = "dogcapture.jpeg";
                elementsThree[i].alt = "dog";
           

                }
            }
        }